site_name: PipelineIO 
site_url: http://pipeline.io
site_author: PipelineIO
site_description: End-to-End ML and AI Model Training and Deployment Platform with GPUs 
repo_url: https://github.com/fluxcapacitor/pipeline/
repo_name: fluxcapacitor/pipeline 
edit_uri: edit/master/docs/
docs_dir: docs
site_dir: site
#strict: true
google_analytics:
  - 'UA-78551725-1'
  - 'auto'
pages:
  - Home: index.md
  - Getting Started: 
    - Product Overview: products/index.md
    - Installing PipelineIO Community Edition: products/install.md
  - CLI and REST API:
    - Command Line Interface: cli/index.md
    - REST API: rest/index.md
  - Train and Deploy a Model:
    - Train a Model: model_train/index.md 
    - Optimize a Model: model_optimize/index.md
    - Deploy a Model: model_deploy/index.md 
  - Model Experiments: model_experiment/index.md
  - Dashboards and Visualizations: model_monitor/index.md
  - Streaming Pipelines: streaming/index.md
  - GPUs and Performance: gpu/index.md  
  - Open Source: open_source/index.md
  - Contribute to PipelineIO: contribute/index.md
  - Community Events: 
    - Meetups: community/index.md
    - Videos and Slides: media/index.md
  - Workshops: workshops/index.md
  - Privacy and Terms: legal/index.md
theme: material
site_favicon: 'img/favicon.png'
extra:
  feature:
    tabs: false
  palette:
    primary: 'orange'
    accent: 'orange'
    extra:
  logo: 'img/pipelineio-logo-128x128.png'
  font:
    text: 'Roboto'
    code: 'Source Code Pro'
  social:
    - type: 'github'
      link: 'https://github.com/fluxcapacitor/pipeline'
    - type: 'meetup'
      link: 'https://www.meetup.com/Advanced-Spark-and-TensorFlow-Meetup/'
    - type: 'youtube'
      link: 'https://youtube.com/channel/UCvlZKtekcKkBUuz8f9dhobw'
    - type: 'slideshare'
      link: 'https://www.slideshare.net/cfregly'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/6609122/'
    - type: 'twitter'
      link: 'https://twitter.com/pipelineio'
    - type: 'docker'
      link: 'https://hub.docker.com/r/fluxcapacitor'
      
markdown_extensions:
  - markdown_include.include:
      base_path: docs 
  - markdown.extensions.admonition
  - markdown.extensions.codehilite(guess_lang=false)
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
extra_css:
  - css/bootstrap_paper.min.css
  - css/style.css
copyright: Copyright &copy; 2017 PipelineIO Inc.
