# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

  - job_name: 'model_server_python'
    static_configs:
      - targets: ['localhost:10254']

  - job_name: 'model_server_tensorflow'
    static_configs:
      - targets: ['localhost:10255']

  - job_name: 'model_server_jvm'
    static_configs:
      - targets: ['localhost:9040']

  - job_name: 'gpu'
    static_configs:
      - targets: ['localhost:7070']

#  - job_name: 'prometheus'
#    static_configs:
#      - targets: ['localhost:9090']
