channels:
  - conda-forge 
dependencies:
  - python=3.6.1=2
  - pip=9.0.1=py36_1
  - mkl=2017.0.1=0
  - mkl-service=1.1.2=py36_3
  - numpy=1.13.1=py36_0
  - pandas=0.20.2
  - scikit-learn=0.18.2
  - ujson=1.35=py36_0
  - pip:
    - pipeline-runtimes>=0.9
