apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
resources:
- application.yaml
commonLabels:
  app.kubernetes.io/name: metadata
  app.kubernetes.io/instance: metadata
  app.kubernetes.io/managed-by: kfctl
  app.kubernetes.io/component: metadata
  app.kubernetes.io/part-of: kubeflow
  app.kubernetes.io/version: v0.6
