markdown:         kramdown
highlighter:      rouge

kramdown:
  auto_ids:       true

permalink:        pretty

source:           src
host:             0.0.0.0
port:             9001
url:              https://www.guild.ai
encoding:         UTF-8

gems:
  - jekyll-redirect-from
  - jekyll-sitemap

title:            Guild AI
description:      Real time TensorFlow&trade; visualization
tagline_main:     Real time TensorFlow&trade; visualization
tagline_sub:      Monitor and compare training runs in real time with<br>Guild AI's easy to use command line toolset
twitter:          guild_ai
authors:          TensorHub and the Guild AI contributors
social_logo_path:
social_image_path:
current_version:  0.1.0
repo:             https://github.com/guildai/guild
tensorflow_min:   1.1.0

download:
  source:
  dist:

cdn:
  # See https://www.srihash.org for info on how to generate the hashes
  css:            https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/css/bootstrap.min.css
  css_hash:       "sha384-AysaV+vQoT3kOAXZkl02PThvDr8HYKPZhNT5h/CXfBThSRXQ6jW5DO2ekP5ViFdi"
  js:             https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/js/bootstrap.min.js
  js_hash:        "sha384-BLiI7JTZm+JWlgKa0M0kGRpJbF2J8q+qreVrKBC47e3K6BW78kGLrCkeRX6I9RoK"
  jquery:         https://code.jquery.com/jquery-3.1.1.min.js
  jquery_hash:    "sha384-3ceskX3iaEnIogmQchP8opvBy3Mi7Ce34nWjpBIwVTHfGYWQS9jwHDVRnpKKHJg7"
  tether:         https://cdnjs.cloudflare.com/ajax/libs/tether/1.3.7/js/tether.min.js
  tether_hash:    "sha384-XTs3FgkjiBgo8qjEjBk0tGmf3wPrWtA6coPfQDfFEY8AnYJwjalXCiosYRBIBZX8"
