dependencies:
  - mkl=2017.0.1=0
  - mkl-service=1.1.2=py36_3
  - numpy=1.13.1=py36_0
  - pip=9.0.1=py36_1
  - python=3.6.1=2
  - pip:
    - grpcio>=0.15.0
    - grpcio-tools>=0.15.0
    - tensorflow>=1.2.0
    - pipeline-ai-runtimes>=0.2
