channels:
  - conda-forge 
dependencies:
  - mkl=2017.0.1=0
  - mkl-service=1.1.2=py36_3
  - openssl=1.0.2l=0
  - pandas=0.20.3=np113py36_0
  - numpy=1.13.1=py36_0
  - pip=9.0.1=py36_1
  - python=3.6.1=2
  - pytz=2017.2=py36_0
  - scikit-learn=0.18.1=np113py36_1
  - scipy=0.19.0=np113py36_0
  - setuptools=27.2.0=py36_0
  - six=1.10.0=py36_0
  - wheel=0.29.0=py36_0
  - h5py=2.7.0=np113py36_0
